Refactor `relativeTime` logic to prevent divergent implementations
clash-lang/clash-compiler pull request #2349
Opened 2022-11-05 12:22 UTC by martijnbastiaan

## Still TODO:

  - [x] ~~Write a changelog entry (see changelog/README.md)~~
  - [ ] Check copyright notices are up to date in edited files
  - [ ] Use `clockTicks` in `asyncRam`
  - [ ] Use `clockTicks` in `trueDualPortBlockRam`

2022-11-05 21:11 UTC, martijnbastiaan commented
@DigitalBrains1 I'm not sure what's up with the failing `asyncRam` unittests. At first I thought they might be sensitive to `ClockB:ClockA:..` vs `ClockA:ClockB:..` but that doesn't seem the case.

2022-11-06 11:49 UTC, DigitalBrains1 commented
This fixes several bugs and comments, and probably leaves one bug in:

```diff
diff --git a/clash-prelude/src/Clash/Explicit/BlockRam.hs b/clash-prelude/src/Clash/Explicit/BlockRam.hs
index 0e1dc6cd0..d35319257 100644
--- a/clash-prelude/src/Clash/Explicit/BlockRam.hs
+++ b/clash-prelude/src/Clash/Explicit/BlockRam.hs
@@ -1290,8 +1290,8 @@ trueDualPortBlockRam# clkA enA weA addrA datA clkB enB weB addrB datB
 
 -- | Haskell model for the primitive 'trueDualPortBlockRam#'.
 --
--- Warning: this model only works if @domFast@'s clock is faster (or equal to)
--- @domSlow@'s clock.
+-- Warning: this model only works if @domFast@'s clock is faster than (or equal
+-- to) @domSlow@'s clock.
 trueDualPortBlockRamModel ::
   forall nAddrs domFast domSlow a .
   ( HasCallStack
@@ -1323,7 +1323,11 @@ trueDualPortBlockRamModel labelA clkA enA weA addrA datA labelB clkB enB weB add
   (outA, outB) =
     go
       (Seq.fromFunction (natToNum @nAddrs) initElement)
-      (clockTicks clkA clkB)
+      -- ensure 'go' hits fast clock first for 2 cycles, then execute slow clock
+      -- for 1 cycle, followed by the regular cadence of either 'ceil(tA / tB)'
+      -- or 'floor(tA / tB)' cycles for the fast clock followed by 1 cycle of
+      -- the slow clock
+      (ClockB : clockTicks clkA clkB)
       (bundle (enA, weA, fromIntegral <$> addrA, datA))
       (bundle (enB, weB, fromIntegral <$> addrB, datB))
       startA startB
diff --git a/clash-prelude/src/Clash/Signal/Internal.hs b/clash-prelude/src/Clash/Signal/Internal.hs
index 000f3375f..39de3a728 100644
--- a/clash-prelude/src/Clash/Signal/Internal.hs
+++ b/clash-prelude/src/Clash/Signal/Internal.hs
@@ -1641,7 +1641,7 @@ clockTicksEither ::
   [ClockAB]
 clockTicksEither clkA clkB =
   case (clkA, clkB) of
-    (Left  tA, Left  tB) | tA == tB -> cycle [ClockB, ClockA]
+    (Left  tA, Left  tB) | tA == tB -> repeat ClockAB
     (Left  tA, Left  tB) -> goStatic tA tB 0
     (Right tA, Right tB) -> goDynamic 0 tA tB
     (Left  tA, Right tB) -> clockTicksEither (Right (pure tA)) (Right tB)
@@ -1661,5 +1661,5 @@ clockTicksEither clkA clkB =
     -- every iteration.
     case compare relativeTime 0 of
       LT -> ClockB  : goDynamic (relativeTime + tB)      tsA         (tB :- tsB)
-      EQ -> ClockAB : goDynamic (relativeTime - tA + tB) tsA         (tB :- tsB)
+      EQ -> ClockAB : goDynamic (relativeTime - tA + tB) tsA         tsB
       GT -> ClockA  : goDynamic (relativeTime - tA)      (tA :- tsA) tsB
```

The issue was that `trueDualPortBlockRam` inserts an extra fast cycle at the start. This process was wrongly described in a comment you deleted, which I also fixed:
```diff
--- ensure 'go' hits fast clock first for 1 cycle, then execute slow
--- clock for 1 cycle, followed by the regular cadence of 'ceil(tA / tB)'
--- cycles for the fast clock followed by 1 cycle of the slow clock
+-- ensure 'go' hits fast clock first for 2 cycles, then execute slow
+-- clock for 1 cycle, followed by the regular cadence of either 'ceil(tA / tB)'
+-- or 'floor(tA / tB)' cycles for the fast clock followed by 1 cycle of
+-- the slow clock
```
However, I doubt this is the correct way to treat it; I think the original code contained a bug. It seems pretty suspect to eat one more `Signal` constructor of the fast clock at the start of your process; if it just changed the processing of the first two (coinciding) clocks from `goBoth` to `goFast`, `goSlow` as it seems to say in the comment before, then that's okay I guess, but that is not what happened. Wouldn't the fast clock machinery be one cycle ahead of the rest of the circuit like this?

The other fixes turned out to have nothing to do with the problem, but they might cause problems later on so might as well point them out now!

(I'm sure that during review of the TDP BRAM PR I've pointed out that
> followed by the regular cadence of `ceil(tA / tB)` cycles for the fast clock followed by 1 cycle of the slow clock

is incorrect. But it somehow snuck back in. If `floor` and `ceiling` differ (which means `ceiling` is one more), then you will see a number of `floor` fast edges before a slow edge, and when the rounding error of `floor` overflows, you'll see `ceiling` fast edges for one time. If it always were `ceiling`, you would not notice a difference in clock speed until it passed an integer ratio between the two, wouldn't that be weird X-D).

2022-11-06 11:57 UTC, DigitalBrains1 commented
I think we should reconstruct the reason that this odd handling of the first few cycles was introduced; what issue it seemed to solve. Then we can think about whether this is correct (seems unlikely, frankly), or what the correct fix is. The tests in `tests/shouldwork/Signal/DualBlockRam{0,1}.hs` don't seem to care either way, they keep passing. That `clash-prelude/tests/Clash/Tests/AsyncFIFOSynchronizer.hs` does care isn't surprising: it tests against generated output that is very picky: it tests data out when the FIFO is empty, and maybe more such pickiness that doesn't actually affect functionality.

2022-11-06 13:29 UTC, martijnbastiaan commented
Ouch those mistakes in `clockTicksEither`..

> I think we should reconstruct the reason that this odd handling of the first few cycles was introduced

I think this was my poor attempt at modelling conflicts in its initial implementation. I mistakenly assumed that _any_ write on the slow domain could conflict with _any_ write on the fast domain. It would therefore do one tick on the slow domain, and do multiple iterations in the fast domain and compare all the reads/writes to see if a conflict occurred.

After [this commit](https://github.com/clash-lang/clash-compiler/commit/212eb9a2a9a4172b3f4d15f651e3a99b477b47db), conflict resolution only happens when the edges exactly coincide (which surely isn't realistic, but will agree with the HDL model). Which leads me to two points I believe to be true:

* The current code doesn't need to know which is the slow domain and which is the fast one.
* The unittests can be changed to match the new output (as long as the HDL matches the model, which seems to be the case).

2022-11-06 16:22 UTC, martijnbastiaan commented
Thanks for all the help @DigitalBrains1. I've listed all the problems you/we found with `trueDualPortBlockRam`. I'll make proper issues later.

2022-11-07 12:23 UTC, DigitalBrains1 requested changes
I have a couple of things, but the rest looks good. Correctly mapping each original primitive, which might swap several symmetrical concepts in processing the clocks, is finicky, but I think you got them all right.

I think there's more code in `clash-prelude/src/Clash/Signal/Internal.hs` that could be changed to make use of the field names in `SDomainConfiguration`, but that doesn't have to be done now (or ever); let's just get this PR done.

2022-11-07 12:25 UTC, martijnbastiaan commented on clash-prelude/src/Clash/Signal/Internal.hs
> +-- SDomainConfiguration {sName = SSymbol @"System", sPeriod = SNat @10000, sActiveEdge = SRising, sResetKind = SAsynchronous, sInitBehavior = SDefined, sResetPolarity = SActiveHigh}
This is tested by doctest, so I don't get a say..

2022-11-07 12:26 UTC, martijnbastiaan commented on clash-prelude/src/Clash/Signal/Internal.hs
> +  SDomainConfiguration ::
Good point

2022-11-07 12:27 UTC, martijnbastiaan commented on clash-prelude/src/Clash/Signal/Internal.hs
> +  (HasCallStack, KnownDomain domA, KnownDomain domB) =>
Yeah you're right. I was thinking you could get an overflow, but you can't; it just silently wraps.

2022-11-07 12:33 UTC, martijnbastiaan commented on clash-prelude/src/Clash/Signal/Internal.hs
> +      GT -> ClockA  : goDynamic (relativeTime - tA)      (tA :- tsA) tsB
FLIP. Yes you're right!

2022-11-07 12:33 UTC, martijnbastiaan commented on clash-prelude/src/Clash/Signal/Internal.hs
> +      GT -> ClockA  : goDynamic (relativeTime - tA)      (tA :- tsA) tsB
I do wonder how this passes the tests.

2022-11-07 12:35 UTC, martijnbastiaan commented on clash-prelude/src/Clash/Signal/Internal.hs
> +      GT -> ClockA  : goDynamic (relativeTime - tA)      (tA :- tsA) tsB
Oh I see. Time to add another test.. :melting-face:

2022-11-07 12:45 UTC, DigitalBrains1 requested changes
My poor comment, you axed it

2022-11-07 12:45 UTC, DigitalBrains1 commented on clash-prelude/src/Clash/Signal/Internal.hs
> + where
```suggestion
 where

    -- Given
    --   tAbsA = absolute time of next active edge of clock A
    --   tAbsB = absolute time of next active edge of clock B
    -- relativeTime is defined as relativeTime = tAbsB - tAbsA
    --
    -- Put differently, relative time 0 points at the next active edge of
    -- clock A, and relativeTime points at the next active edge of clock B.
```

2022-11-07 12:47 UTC, DigitalBrains1 commented on clash-prelude/src/Clash/Signal/Internal.hs
> +-- SDomainConfiguration {sName = SSymbol @"System", sPeriod = SNat @10000, sActiveEdge = SRising, sResetKind = SAsynchronous, sInitBehavior = SDefined, sResetPolarity = SActiveHigh}
`doctest` checks that we _don't_ conform to our own style guide?? (the as yet unwritten section of it)

2022-11-07 15:18 UTC, martijnbastiaan commented
I've enabled auto-merge @DigitalBrains1; if you're happy it will merge on your approval.

2022-11-07 15:30 UTC, lmbollen commented
> I've enabled auto-merge @DigitalBrains1; if you're happy it will merge on your approval.
> 
> edit: to prevent confusion it will also merge if you're sad on your approval.

I'm confused, what if he's indifferent?

2022-11-07 16:50 UTC, DigitalBrains1 commented on clash-prelude/tests/Clash/Tests/Signal.hs
> +  print actual
This seems to be a left over debugging statement which outputs text every test bench run

2022-11-07 17:54 UTC, DigitalBrains1 approved these changes

2022-11-07 18:19 UTC, merged